In [3]:
import pandas
import json

In [2]:
pandas.read_json('/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-1.json')

           type                                               data
rows          1  [{'LAT': '42.33257', 'LON': '-70.98719', 'SPEE...
areaShips     1                                               2335

In [6]:
file = open('/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-1.json')
data = json.load(file)

In [10]:
pandas.DataFrame(data['data']['rows'])

,LAT,LON,SPEED,COURSE,HEADING,ELAPSED,DESTINATION,FLAG,LENGTH,ROT,...,SHIPTYPE,SHIP_ID,WIDTH,L_FORE,W_LEFT,DWT,GT_SHIPTYPE,TYPE_IMG,TYPE_NAME,STATUS_NAME
0,42.33257,-70.98719,78,273,272,0,BOSTON,LR,333,4,...,7,6836077,48,135,29,130573,11,NaN,NaN,NaN
1,6.4305,3.337632,0,122,308,1,LAGOS,SG,249,0,...,8,373669,45,215,31,119456,17,NaN,NaN,NaN
2,41.49677,-81.723,0,217,54,1,SHUTTLES,US,193,0,...,7,437518,20,183,15,27393,6,NaN,NaN,NaN
3,44.03703,9.22885,106,130,129,0,IT GOA>IT SPE,LR,366,-2,...,7,6519259,51,112,18,160357,11,NaN,NaN,NaN
4,17.12816,-62.11969,172,264,260,1,KNBAS,VC,159,0,...,7,467300,22,143,23,12418,11,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2330,-3.112293,-7.352088,97,147,None,29,NaN,NaN,NaN,NaN,...,7,TmpZeE56ZzBOall4TnpnME5qWXhOdz09LVRSTWFHU0hFbV...,NaN,NaN,NaN,NaN,NaN,7,Cargo Vessel,Underway using Engine
2331,-5.607378,-6.881757,98,146,None,29,NaN,NaN,NaN,NaN,...,7,TVRneE1qQTRNVGd4TWpBNE1UZ3hNZz09LW94WE5LbHVmSG...,NaN,NaN,NaN,NaN,NaN,7,Cargo Vessel,Underway using Engine
2332,8.208878,-24.8054,126,207,None,584,BR RIG,HK,199,NaN,...,7,5556631,30,170,19,46500,9,NaN,NaN,NaN
2333,6.43999,-25.69832,129,205,None,29,NaN,NaN,NaN,NaN,...,7,TWpNMk1URTVNak0yTVRFNU1qTTJNUT09LTZsU25WYWhxRE...,NaN,NaN,NaN,NaN,NaN,7,Cargo Vessel,Underway using Engine
2334,4.431993,-26.74682,171,135,None,29,NaN,NaN,NaN,NaN,...,7,TlRZME5ERTVOVFkwTkRFNU5UWTBOQT09LVNmVTl5YkZxTk...,NaN,NaN,NaN,NaN,NaN,7,Cargo Vessel,Underway using Engine

In [13]:
file_list = ['/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-1.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-2.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-3.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-4.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-5.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-6.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-7.json',
             '/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-8.json']

file = open('/Users/baird/Dropbox/_gem-docs/external-orgs/earthjustice/station_0-1.json')
data = json.load(file)
marine_traffic_df = pandas.DataFrame(data['data']['rows'])
for f in file_list[1:]:
    file = open(f)
    data = json.load(file)
    temp_df = pandas.DataFrame(data['data']['rows'])
    marine_traffic_df = pandas.concat([marine_traffic_df, temp_df], ignore_index=True)

In [19]:
marine_traffic_df.loc[marine_traffic_df.GT_SHIPTYPE=='18'].to_csv('/Users/Baird/Dropbox/_gem-docs/external-orgs/earthjustice/MarineTraffic-LNGTankers-2024-04-30.csv')